apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "netd.fullname" . }}
  labels:
    {{- include "netd.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "netd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "netd.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ include "netd.serviceAccountName" . }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: CONFIG_PATH
              value: /config/config.yaml
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "netd.fullname" . }}-config
        {{- toYaml .Values.volumes | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
