import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const appRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(appRoot, "..", "..", "..");
const docsSourceRoot = path.join(repoRoot, "skills", "sandbox0", "references", "docs-src");
const manifestPath = path.join(docsSourceRoot, "manifest.json");
const generatedDocsRoot = path.join(appRoot, "src", "generated", "docs");
const generatedPagesRoot = path.join(generatedDocsRoot, "pages");

async function main() {
  const manifest = await readManifest();
  const entries = flattenManifest(manifest);

  await validateManifest(manifest, entries);
  await fs.mkdir(generatedDocsRoot, { recursive: true });
  await fs.rm(generatedPagesRoot, { recursive: true, force: true });

  for (const entry of entries) {
    const targetPath = path.join(generatedPagesRoot, entry.sourcePath);
    await fs.mkdir(path.dirname(targetPath), { recursive: true });
    await fs.copyFile(entry.sourceFilePath, targetPath);
  }

  await fs.writeFile(
    path.join(generatedDocsRoot, "content.tsx"),
    `${buildContentModule(manifest.defaultPage, entries)}\n`
  );
  await fs.writeFile(
    path.join(generatedDocsRoot, "navigation.ts"),
    `${buildNavigationModule(entries)}\n`
  );

  console.log(`generated docs registry for ${entries.length} pages from ${path.relative(repoRoot, docsSourceRoot)}`);
}

async function readManifest() {
  const raw = await fs.readFile(manifestPath, "utf8");
  return JSON.parse(raw);
}

function flattenManifest(manifest) {
  return manifest.sections.flatMap((section) => {
    const sectionRootPage = section.pages.find((page) => page.slug === "") ?? section.pages[0];
    const sectionHref = toDocsHref(buildPageKey(section.slug, sectionRootPage.slug));

    return section.pages.map((page) => {
      const pageKey = buildPageKey(section.slug, page.slug);
      const pathSegments = pageKey.split("/");
      const importName = `${toPascalCase(pathSegments)}Page`;

      return {
        importName,
        pageKey,
        href: toDocsHref(pageKey),
        label: page.title,
        sectionHref,
        sectionLabel: section.label,
        sourcePath: path.posix.join(...pathSegments, "page.mdx"),
        sourceFilePath: path.join(docsSourceRoot, ...pathSegments, "page.mdx"),
      };
    });
  });
}

async function validateManifest(manifest, entries) {
  if (!manifest || typeof manifest !== "object") {
    throw new Error("docs manifest must be an object");
  }

  if (typeof manifest.defaultPage !== "string" || manifest.defaultPage.length === 0) {
    throw new Error("docs manifest defaultPage must be a non-empty string");
  }

  const pageKeys = new Set();
  let hasDefaultPage = false;

  for (const entry of entries) {
    if (pageKeys.has(entry.pageKey)) {
      throw new Error(`duplicate docs page key: ${entry.pageKey}`);
    }
    pageKeys.add(entry.pageKey);
    hasDefaultPage ||= entry.pageKey === manifest.defaultPage;

    try {
      await fs.access(entry.sourceFilePath);
    } catch {
      throw new Error(`missing docs source file: ${path.relative(repoRoot, entry.sourceFilePath)}`);
    }
  }

  if (!hasDefaultPage) {
    throw new Error(`docs defaultPage "${manifest.defaultPage}" does not exist in manifest`);
  }
}

function buildContentModule(defaultPage, entries) {
  const imports = entries
    .map((entry) => `import ${entry.importName} from "./pages/${entry.sourcePath}";`)
    .join("\n");
  const registryLines = entries
    .map((entry) => `  "${entry.pageKey}": ${entry.importName},`)
    .join("\n");
  const slugs = entries.map((entry) => `"${entry.pageKey}"`).join(", ");

  return [
    "// Generated by scripts/generate_docs_content.mjs. Do not edit manually.",
    'import { notFound } from "next/navigation";',
    'import type { ComponentType } from "react";',
    imports,
    "",
    "const docsPageRegistry: Record<string, ComponentType> = {",
    registryLines,
    "};",
    "",
    `export const defaultDocsPageSlug = "${defaultPage}";`,
    `export const docsPageSlugs = [${slugs}] as const;`,
    "",
    "export function renderDocsPage(slug: string[]) {",
    '  const pageKey = slug.join("/");',
    "  const Page = docsPageRegistry[pageKey];",
    "",
    "  if (!Page) {",
    "    notFound();",
    "  }",
    "",
    "  return <Page />;",
    "}",
  ].join("\n");
}

function buildNavigationModule(entries) {
  const sections = new Map();

  for (const entry of entries) {
    if (!sections.has(entry.sectionLabel)) {
      sections.set(entry.sectionLabel, {
        label: entry.sectionLabel,
        href: entry.sectionHref,
        items: [],
      });
    }

    sections.get(entry.sectionLabel).items.push({
      label: entry.label,
      href: entry.href,
    });
  }

  return [
    "// Generated by scripts/generate_docs_content.mjs. Do not edit manually.",
    'import type { PixelSidebarItem } from "@/components/docs/PixelSidebar";',
    'import { toVersionedDocsHref } from "@/components/docs/versioning";',
    "",
    `const baseDocsNavigation: PixelSidebarItem[] = ${JSON.stringify(
      [...sections.values()],
      null,
      2
    )};`,
    "",
    "function mapItem(version: string, item: PixelSidebarItem): PixelSidebarItem {",
    "  return {",
    "    ...item,",
    "    href: toVersionedDocsHref(version, item.href),",
    "    items: item.items?.map((child) => mapItem(version, child)),",
    "  };",
    "}",
    "",
    "export function buildDocsNavigation(version: string): PixelSidebarItem[] {",
    "  return baseDocsNavigation.map((item) => mapItem(version, item));",
    "}",
  ].join("\n");
}

function buildPageKey(sectionSlug, pageSlug) {
  const normalizedSectionSlug = normalizeSlug(sectionSlug);
  const normalizedPageSlug = normalizeSlug(pageSlug);
  return normalizedPageSlug.length > 0
    ? `${normalizedSectionSlug}/${normalizedPageSlug}`
    : normalizedSectionSlug;
}

function normalizeSlug(value) {
  if (typeof value !== "string") {
    throw new Error("docs slug must be a string");
  }

  return value
    .split("/")
    .map((segment) => segment.trim())
    .filter(Boolean)
    .join("/");
}

function toDocsHref(pageKey) {
  return `/docs/${pageKey}`;
}

function toPascalCase(segments) {
  return segments
    .flatMap((segment) => segment.split(/[^A-Za-z0-9]+/))
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join("");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
