apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "infra-operator.fullname" . }}-config
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    imageRepo: {{ .Values.image.repository }}
    imageTag: {{ .Values.image.tag | default .Chart.AppVersion }}
    {{ if .Values.config.imagePullPolicy }}
    imagePullPolicy: {{ .Values.config.imagePullPolicy }}
    {{ end }}
