{{- $role := .Files.Get "files/clusterrole.yaml" | fromYaml }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "infra-operator.fullname" . }}-manager-role
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
rules:
{{- $role.rules | toYaml | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "infra-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "infra-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "infra-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "infra-operator.fullname" . }}-leader-election-role
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "infra-operator.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "infra-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "infra-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "infra-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
