version: "2"

linters:
  default: none
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "ST1000:"
      - linters:
          - staticcheck
        text: "ST1003:"
      - linters:
          - staticcheck
        text: "ST1020:"
      - linters:
          - staticcheck
        text: "ST1021:"
      - linters:
          - staticcheck
        text: "SA1019:"
