apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manager.fullname" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := deepCopy .Values.config }}
    {{- if and .Values.global .Values.global.database }}
    {{- if not $config.database_url }}
    {{- $_ := set $config "database_url" .Values.global.database.url }}
    {{- end }}
    {{- end }}
    {{- if not $config.manager_image }}
    {{- $managerTag := .Values.image.tag | default .Chart.AppVersion }}
    {{- $_ := set $config "manager_image" (printf "%s:%s" .Values.image.repository $managerTag) }}
    {{- end }}
    {{- $config | toYaml | nindent 4 }}
