apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "manager.fullname" . }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "manager.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONFIG_PATH
              value: "/config/config.yaml"
          ports:
            - name: http
              containerPort: {{ .Values.config.http_port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.config.metrics_port }}
              protocol: TCP
            {{- if .Values.webhook.enabled }}
            - name: webhook
              containerPort: {{ .Values.config.webhook_port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: internal-jwt-private-key
              mountPath: /secrets
              readOnly: true
            - name: internal-jwt-public-key
              mountPath: /config/internal_jwt_public.key
              subPath: internal_jwt_public.key
              readOnly: true
            {{- if .Values.webhook.enabled }}
            - name: webhook-certs
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "manager.fullname" . }}
        - name: internal-jwt-private-key
          secret:
            secretName: {{ .Values.secrets.internalJwtSecretName }}
            items:
              - key: {{ .Values.secrets.internalJwtPrivateKeyKey }}
                path: internal_jwt_private.key
        - name: internal-jwt-public-key
          secret:
            secretName: {{ .Values.secrets.internalJwtSecretName }}
            items:
              - key: {{ .Values.secrets.internalJwtPublicKeyKey }}
                path: internal_jwt_public.key
        {{- if .Values.webhook.enabled }}
        - name: webhook-certs
          secret:
            {{- if .Values.webhook.tls.certSecretName }}
            secretName: {{ .Values.webhook.tls.certSecretName }}
            {{- else }}
            secretName: {{ include "manager.fullname" . }}-webhook-certs
            {{- end }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
