{{- if .Values.sandboxNamespace.create }}
{{- $ns := .Values.config.default_template_namespace }}
{{- if not (lookup "v1" "Namespace" "" $ns) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: sandbox0
    sandbox0.ai/namespace-type: "templates"
  annotations:
    # Create namespace before manager starts (using pre-install hook)
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
{{- end }}
{{- end }}
