{{- if .Values.webhook.enabled -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "manager.fullname" . }}-validating-webhook
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "manager.fullname" . }}-serving-cert
  labels:
    {{- include "manager.labels" . | nindent 4 }}
webhooks:
  - name: vsandboxtemplate.sandbox0.ai
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /validate-sandboxtemplate
        port: {{ .Values.service.webhookPort }}
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - sandbox0.ai
        apiVersions:
          - v1alpha1
        resources:
          - sandboxtemplates
    failurePolicy: Fail
    sideEffects: None
{{- end }}
