affinity: {}
config:
    base_url: http://localhost:8080
    built_in_auth:
        admin_only: false
        allow_registration: false
        email_verification_required: false
        enabled: true
        init_user:
            email: admin@localhost
            name: Admin
            password: admin123
    database_url: ""
    default_internal_gateway_url: http://internal-gateway.sandbox0-system:8443
    edition: self-hosted
    http_port: 8080
    jwt_access_token_ttl: 15m0s
    jwt_refresh_token_ttl: 168h0m0s
    jwt_secret: ""
    log_level: info
    oidc_providers: []
    proxy_timeout: 30s
    rate_limit_burst: 200
    rate_limit_rps: 100
    scheduler_enabled: false
    scheduler_url: ""
    shutdown_timeout: 30s
fullnameOverride: ""
image:
    pullPolicy: IfNotPresent
    repository: sandbox0ai/infra
    tag: ""
imagePullSecrets: []
ingress:
    annotations: {}
    className: ""
    enabled: false
    hosts:
        - host: edge-gateway.local
          paths:
            - path: /
              pathType: Prefix
    tls: []
livenessProbe:
    httpGet:
        path: /healthz
        port: http
    initialDelaySeconds: 10
    periodSeconds: 10
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe:
    httpGet:
        path: /readyz
        port: http
    initialDelaySeconds: 5
    periodSeconds: 5
replicaCount: 1
resources:
    limits:
        cpu: 500m
        memory: 256Mi
    requests:
        cpu: 100m
        memory: 128Mi
secrets:
    internalJwtPrivateKeyKey: ""
    internalJwtSecretName: ""
securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
service:
    port: 8080
    type: ClusterIP
serviceAccount:
    annotations: {}
    automount: true
    create: true
    name: ""
tolerations: []
