apiVersion: v1
kind: ConfigMap
metadata:
  name: netd-config
  namespace: sandbox0-system
data:
  # Configure these based on your cluster setup
  storage-proxy-cidr: ""
  cluster-dns-cidr: "10.96.0.10/32"
  internal-gateway-cidr: ""

