-- +goose Up
ALTER TABLE sandbox_volumes
DROP COLUMN IF EXISTS cache_size,
DROP COLUMN IF EXISTS prefetch,
DROP COLUMN IF EXISTS buffer_size,
DROP COLUMN IF EXISTS writeback;

-- +goose Down
ALTER TABLE sandbox_volumes
ADD COLUMN IF NOT EXISTS cache_size TEXT NOT NULL DEFAULT '1G',
ADD COLUMN IF NOT EXISTS prefetch INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS buffer_size TEXT NOT NULL DEFAULT '32M',
ADD COLUMN IF NOT EXISTS writeback BOOLEAN NOT NULL DEFAULT false;
