//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package config

import (
	"k8s.io/api/core/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalerConfig) DeepCopyInto(out *AutoscalerConfig) {
	*out = *in
	out.MinScaleInterval = in.MinScaleInterval
	out.NoTrafficScaleDownAfter = in.NoTrafficScaleDownAfter
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalerConfig.
func (in *AutoscalerConfig) DeepCopy() *AutoscalerConfig {
	if in == nil {
		return nil
	}
	out := new(AutoscalerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuiltInAuthConfig) DeepCopyInto(out *BuiltInAuthConfig) {
	*out = *in
	if in.InitUser != nil {
		in, out := &in.InitUser, &out.InitUser
		*out = new(InitUserConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuiltInAuthConfig.
func (in *BuiltInAuthConfig) DeepCopy() *BuiltInAuthConfig {
	if in == nil {
		return nil
	}
	out := new(BuiltInAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigError) DeepCopyInto(out *ConfigError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigError.
func (in *ConfigError) DeepCopy() *ConfigError {
	if in == nil {
		return nil
	}
	out := new(ConfigError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePoolConfig) DeepCopyInto(out *DatabasePoolConfig) {
	*out = *in
	out.MaxConnLifetime = in.MaxConnLifetime
	out.MaxConnIdleTime = in.MaxConnIdleTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePoolConfig.
func (in *DatabasePoolConfig) DeepCopy() *DatabasePoolConfig {
	if in == nil {
		return nil
	}
	out := new(DatabasePoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeGatewayConfig) DeepCopyInto(out *EdgeGatewayConfig) {
	*out = *in
	out.InternalAuthTTL = in.InternalAuthTTL
	out.ClusterCacheTTL = in.ClusterCacheTTL
	out.ProxyTimeout = in.ProxyTimeout
	out.ShutdownTimeout = in.ShutdownTimeout
	out.ServerReadTimeout = in.ServerReadTimeout
	out.ServerWriteTimeout = in.ServerWriteTimeout
	out.ServerIdleTimeout = in.ServerIdleTimeout
	in.GatewayConfig.DeepCopyInto(&out.GatewayConfig)
	in.Registry.DeepCopyInto(&out.Registry)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeGatewayConfig.
func (in *EdgeGatewayConfig) DeepCopy() *EdgeGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(EdgeGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	out.JWTAccessTokenTTL = in.JWTAccessTokenTTL
	out.JWTRefreshTokenTTL = in.JWTRefreshTokenTTL
	out.RateLimitCleanupInterval = in.RateLimitCleanupInterval
	in.BuiltInAuth.DeepCopyInto(&out.BuiltInAuth)
	if in.OIDCProviders != nil {
		in, out := &in.OIDCProviders, &out.OIDCProviders
		*out = make([]OIDCProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.OIDCStateTTL = in.OIDCStateTTL
	out.OIDCStateCleanupInterval = in.OIDCStateCleanupInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitUserConfig) DeepCopyInto(out *InitUserConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitUserConfig.
func (in *InitUserConfig) DeepCopy() *InitUserConfig {
	if in == nil {
		return nil
	}
	out := new(InitUserConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalGatewayConfig) DeepCopyInto(out *InternalGatewayConfig) {
	*out = *in
	if in.AllowedCallers != nil {
		in, out := &in.AllowedCallers, &out.AllowedCallers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ShutdownTimeout = in.ShutdownTimeout
	out.HealthCheckPeriod = in.HealthCheckPeriod
	out.ProxyTimeout = in.ProxyTimeout
	in.GatewayConfig.DeepCopyInto(&out.GatewayConfig)
	if in.SchedulerPermissions != nil {
		in, out := &in.SchedulerPermissions, &out.SchedulerPermissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcdStoragePermissions != nil {
		in, out := &in.ProcdStoragePermissions, &out.ProcdStoragePermissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalGatewayConfig.
func (in *InternalGatewayConfig) DeepCopy() *InternalGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(InternalGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfig) DeepCopyInto(out *ManagerConfig) {
	*out = *in
	out.ResyncPeriod = in.ResyncPeriod
	out.CleanupInterval = in.CleanupInterval
	out.DefaultSandboxTTL = in.DefaultSandboxTTL
	out.NetdPolicyApplyTimeout = in.NetdPolicyApplyTimeout
	out.NetdPolicyApplyPollInterval = in.NetdPolicyApplyPollInterval
	out.ProcdClientTimeout = in.ProcdClientTimeout
	out.ProcdInitTimeout = in.ProcdInitTimeout
	out.ShutdownTimeout = in.ShutdownTimeout
	in.ProcdConfig.DeepCopyInto(&out.ProcdConfig)
	in.Registry.DeepCopyInto(&out.Registry)
	out.Autoscaler = in.Autoscaler
	in.SandboxPodPlacement.DeepCopyInto(&out.SandboxPodPlacement)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfig.
func (in *ManagerConfig) DeepCopy() *ManagerConfig {
	if in == nil {
		return nil
	}
	out := new(ManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetdConfig) DeepCopyInto(out *NetdConfig) {
	*out = *in
	out.ResyncPeriod = in.ResyncPeriod
	if in.PreferNFT != nil {
		in, out := &in.PreferNFT, &out.PreferNFT
		*out = new(bool)
		**out = **in
	}
	out.ProxyUpstreamTimeout = in.ProxyUpstreamTimeout
	if in.PlatformAllowedCIDRs != nil {
		in, out := &in.PlatformAllowedCIDRs, &out.PlatformAllowedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PlatformDeniedCIDRs != nil {
		in, out := &in.PlatformDeniedCIDRs, &out.PlatformDeniedCIDRs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PlatformAllowedDomains != nil {
		in, out := &in.PlatformAllowedDomains, &out.PlatformAllowedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PlatformDeniedDomains != nil {
		in, out := &in.PlatformDeniedDomains, &out.PlatformDeniedDomains
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.EDTHorizon = in.EDTHorizon
	out.MetricsReportInterval = in.MetricsReportInterval
	out.ShutdownDelay = in.ShutdownDelay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetdConfig.
func (in *NetdConfig) DeepCopy() *NetdConfig {
	if in == nil {
		return nil
	}
	out := new(NetdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCProviderConfig) DeepCopyInto(out *OIDCProviderConfig) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TeamMapping != nil {
		in, out := &in.TeamMapping, &out.TeamMapping
		*out = new(TeamMappingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCProviderConfig.
func (in *OIDCProviderConfig) DeepCopy() *OIDCProviderConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorConfig) DeepCopyInto(out *OperatorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorConfig.
func (in *OperatorConfig) DeepCopy() *OperatorConfig {
	if in == nil {
		return nil
	}
	out := new(OperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcdConfig) DeepCopyInto(out *ProcdConfig) {
	*out = *in
	out.CacheTTL = in.CacheTTL
	out.ContextCleanupInterval = in.ContextCleanupInterval
	out.ContextIdleTimeout = in.ContextIdleTimeout
	out.ContextMaxLifetime = in.ContextMaxLifetime
	out.ContextFinishedTTL = in.ContextFinishedTTL
	out.WebhookRequestTimeout = in.WebhookRequestTimeout
	out.WebhookBaseBackoff = in.WebhookBaseBackoff
	if in.setKeys != nil {
		in, out := &in.setKeys, &out.setKeys
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcdConfig.
func (in *ProcdConfig) DeepCopy() *ProcdConfig {
	if in == nil {
		return nil
	}
	out := new(ProcdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAWSConfig) DeepCopyInto(out *RegistryAWSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAWSConfig.
func (in *RegistryAWSConfig) DeepCopy() *RegistryAWSConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryAWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAliyunConfig) DeepCopyInto(out *RegistryAliyunConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAliyunConfig.
func (in *RegistryAliyunConfig) DeepCopy() *RegistryAliyunConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryAliyunConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryAzureConfig) DeepCopyInto(out *RegistryAzureConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryAzureConfig.
func (in *RegistryAzureConfig) DeepCopy() *RegistryAzureConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryAzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryBuiltinConfig) DeepCopyInto(out *RegistryBuiltinConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryBuiltinConfig.
func (in *RegistryBuiltinConfig) DeepCopy() *RegistryBuiltinConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryBuiltinConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryConfig) DeepCopyInto(out *RegistryConfig) {
	*out = *in
	if in.AWS != nil {
		in, out := &in.AWS, &out.AWS
		*out = new(RegistryAWSConfig)
		**out = **in
	}
	if in.GCP != nil {
		in, out := &in.GCP, &out.GCP
		*out = new(RegistryGCPConfig)
		**out = **in
	}
	if in.Azure != nil {
		in, out := &in.Azure, &out.Azure
		*out = new(RegistryAzureConfig)
		**out = **in
	}
	if in.Aliyun != nil {
		in, out := &in.Aliyun, &out.Aliyun
		*out = new(RegistryAliyunConfig)
		**out = **in
	}
	if in.Harbor != nil {
		in, out := &in.Harbor, &out.Harbor
		*out = new(RegistryHarborConfig)
		**out = **in
	}
	if in.Builtin != nil {
		in, out := &in.Builtin, &out.Builtin
		*out = new(RegistryBuiltinConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryConfig.
func (in *RegistryConfig) DeepCopy() *RegistryConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryGCPConfig) DeepCopyInto(out *RegistryGCPConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryGCPConfig.
func (in *RegistryGCPConfig) DeepCopy() *RegistryGCPConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryGCPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryHarborConfig) DeepCopyInto(out *RegistryHarborConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryHarborConfig.
func (in *RegistryHarborConfig) DeepCopy() *RegistryHarborConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryHarborConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPodPlacementConfig) DeepCopyInto(out *SandboxPodPlacementConfig) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPodPlacementConfig.
func (in *SandboxPodPlacementConfig) DeepCopy() *SandboxPodPlacementConfig {
	if in == nil {
		return nil
	}
	out := new(SandboxPodPlacementConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerConfig) DeepCopyInto(out *SchedulerConfig) {
	*out = *in
	out.ReconcileInterval = in.ReconcileInterval
	out.ShutdownTimeout = in.ShutdownTimeout
	out.ReadTimeout = in.ReadTimeout
	out.WriteTimeout = in.WriteTimeout
	out.IdleTimeout = in.IdleTimeout
	out.ProxyTimeout = in.ProxyTimeout
	out.DatabasePool = in.DatabasePool
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerConfig.
func (in *SchedulerConfig) DeepCopy() *SchedulerConfig {
	if in == nil {
		return nil
	}
	out := new(SchedulerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageProxyConfig) DeepCopyInto(out *StorageProxyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageProxyConfig.
func (in *StorageProxyConfig) DeepCopy() *StorageProxyConfig {
	if in == nil {
		return nil
	}
	out := new(StorageProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMappingConfig) DeepCopyInto(out *TeamMappingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMappingConfig.
func (in *TeamMappingConfig) DeepCopy() *TeamMappingConfig {
	if in == nil {
		return nil
	}
	out := new(TeamMappingConfig)
	in.DeepCopyInto(out)
	return out
}
