//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package config

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuiltInAuthConfig) DeepCopyInto(out *BuiltInAuthConfig) {
	*out = *in
	if in.InitUser != nil {
		in, out := &in.InitUser, &out.InitUser
		*out = new(InitUserConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuiltInAuthConfig.
func (in *BuiltInAuthConfig) DeepCopy() *BuiltInAuthConfig {
	if in == nil {
		return nil
	}
	out := new(BuiltInAuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CiliumConfig) DeepCopyInto(out *CiliumConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CiliumConfig.
func (in *CiliumConfig) DeepCopy() *CiliumConfig {
	if in == nil {
		return nil
	}
	out := new(CiliumConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigError) DeepCopyInto(out *ConfigError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigError.
func (in *ConfigError) DeepCopy() *ConfigError {
	if in == nil {
		return nil
	}
	out := new(ConfigError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabasePoolConfig) DeepCopyInto(out *DatabasePoolConfig) {
	*out = *in
	out.MaxConnLifetime = in.MaxConnLifetime
	out.MaxConnIdleTime = in.MaxConnIdleTime
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabasePoolConfig.
func (in *DatabasePoolConfig) DeepCopy() *DatabasePoolConfig {
	if in == nil {
		return nil
	}
	out := new(DatabasePoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultTemplateConfig) DeepCopyInto(out *DefaultTemplateConfig) {
	*out = *in
	out.Pool = in.Pool
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultTemplateConfig.
func (in *DefaultTemplateConfig) DeepCopy() *DefaultTemplateConfig {
	if in == nil {
		return nil
	}
	out := new(DefaultTemplateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultTemplatePoolConfig) DeepCopyInto(out *DefaultTemplatePoolConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultTemplatePoolConfig.
func (in *DefaultTemplatePoolConfig) DeepCopy() *DefaultTemplatePoolConfig {
	if in == nil {
		return nil
	}
	out := new(DefaultTemplatePoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EdgeGatewayConfig) DeepCopyInto(out *EdgeGatewayConfig) {
	*out = *in
	out.InternalAuthTTL = in.InternalAuthTTL
	out.ClusterCacheTTL = in.ClusterCacheTTL
	out.ProxyTimeout = in.ProxyTimeout
	out.ShutdownTimeout = in.ShutdownTimeout
	out.ServerReadTimeout = in.ServerReadTimeout
	out.ServerWriteTimeout = in.ServerWriteTimeout
	out.ServerIdleTimeout = in.ServerIdleTimeout
	in.GatewayConfig.DeepCopyInto(&out.GatewayConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EdgeGatewayConfig.
func (in *EdgeGatewayConfig) DeepCopy() *EdgeGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(EdgeGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayConfig) DeepCopyInto(out *GatewayConfig) {
	*out = *in
	out.JWTAccessTokenTTL = in.JWTAccessTokenTTL
	out.JWTRefreshTokenTTL = in.JWTRefreshTokenTTL
	out.RateLimitCleanupInterval = in.RateLimitCleanupInterval
	in.BuiltInAuth.DeepCopyInto(&out.BuiltInAuth)
	if in.OIDCProviders != nil {
		in, out := &in.OIDCProviders, &out.OIDCProviders
		*out = make([]OIDCProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.OIDCStateTTL = in.OIDCStateTTL
	out.OIDCStateCleanupInterval = in.OIDCStateCleanupInterval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayConfig.
func (in *GatewayConfig) DeepCopy() *GatewayConfig {
	if in == nil {
		return nil
	}
	out := new(GatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitUserConfig) DeepCopyInto(out *InitUserConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitUserConfig.
func (in *InitUserConfig) DeepCopy() *InitUserConfig {
	if in == nil {
		return nil
	}
	out := new(InitUserConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalGatewayConfig) DeepCopyInto(out *InternalGatewayConfig) {
	*out = *in
	if in.AllowedCallers != nil {
		in, out := &in.AllowedCallers, &out.AllowedCallers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ShutdownTimeout = in.ShutdownTimeout
	out.HealthCheckPeriod = in.HealthCheckPeriod
	out.ProxyTimeout = in.ProxyTimeout
	in.GatewayConfig.DeepCopyInto(&out.GatewayConfig)
	if in.SchedulerPermissions != nil {
		in, out := &in.SchedulerPermissions, &out.SchedulerPermissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProcdStoragePermissions != nil {
		in, out := &in.ProcdStoragePermissions, &out.ProcdStoragePermissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalGatewayConfig.
func (in *InternalGatewayConfig) DeepCopy() *InternalGatewayConfig {
	if in == nil {
		return nil
	}
	out := new(InternalGatewayConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagerConfig) DeepCopyInto(out *ManagerConfig) {
	*out = *in
	if in.DefaultTemplate != nil {
		in, out := &in.DefaultTemplate, &out.DefaultTemplate
		*out = new(DefaultTemplateConfig)
		**out = **in
	}
	out.ResyncPeriod = in.ResyncPeriod
	out.CleanupInterval = in.CleanupInterval
	out.DefaultSandboxTTL = in.DefaultSandboxTTL
	out.Network = in.Network
	out.ProcdClientTimeout = in.ProcdClientTimeout
	out.ShutdownTimeout = in.ShutdownTimeout
	in.ProcdConfig.DeepCopyInto(&out.ProcdConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagerConfig.
func (in *ManagerConfig) DeepCopy() *ManagerConfig {
	if in == nil {
		return nil
	}
	out := new(ManagerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkProviderConfig) DeepCopyInto(out *NetworkProviderConfig) {
	*out = *in
	out.Cilium = in.Cilium
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkProviderConfig.
func (in *NetworkProviderConfig) DeepCopy() *NetworkProviderConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCProviderConfig) DeepCopyInto(out *OIDCProviderConfig) {
	*out = *in
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TeamMapping != nil {
		in, out := &in.TeamMapping, &out.TeamMapping
		*out = new(TeamMappingConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCProviderConfig.
func (in *OIDCProviderConfig) DeepCopy() *OIDCProviderConfig {
	if in == nil {
		return nil
	}
	out := new(OIDCProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorConfig) DeepCopyInto(out *OperatorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorConfig.
func (in *OperatorConfig) DeepCopy() *OperatorConfig {
	if in == nil {
		return nil
	}
	out := new(OperatorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProcdConfig) DeepCopyInto(out *ProcdConfig) {
	*out = *in
	out.CacheTTL = in.CacheTTL
	out.WebhookRequestTimeout = in.WebhookRequestTimeout
	out.WebhookBaseBackoff = in.WebhookBaseBackoff
	if in.setKeys != nil {
		in, out := &in.setKeys, &out.setKeys
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProcdConfig.
func (in *ProcdConfig) DeepCopy() *ProcdConfig {
	if in == nil {
		return nil
	}
	out := new(ProcdConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulerConfig) DeepCopyInto(out *SchedulerConfig) {
	*out = *in
	out.ReconcileInterval = in.ReconcileInterval
	out.ShutdownTimeout = in.ShutdownTimeout
	out.ReadTimeout = in.ReadTimeout
	out.WriteTimeout = in.WriteTimeout
	out.IdleTimeout = in.IdleTimeout
	out.ProxyTimeout = in.ProxyTimeout
	out.DatabasePool = in.DatabasePool
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulerConfig.
func (in *SchedulerConfig) DeepCopy() *SchedulerConfig {
	if in == nil {
		return nil
	}
	out := new(SchedulerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageProxyConfig) DeepCopyInto(out *StorageProxyConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageProxyConfig.
func (in *StorageProxyConfig) DeepCopy() *StorageProxyConfig {
	if in == nil {
		return nil
	}
	out := new(StorageProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamMappingConfig) DeepCopyInto(out *TeamMappingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamMappingConfig.
func (in *TeamMappingConfig) DeepCopy() *TeamMappingConfig {
	if in == nil {
		return nil
	}
	out := new(TeamMappingConfig)
	in.DeepCopyInto(out)
	return out
}
