apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edge-gateway.fullname" . }}
  labels:
    {{- include "edge-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := deepCopy .Values.config }}
    {{- if and .Values.global .Values.global.database }}
    {{- if not $config.database_url }}
    {{- $_ := set $config "database_url" .Values.global.database.url }}
    {{- end }}
    {{- end }}
    {{- if and .Values.global .Values.global.jwt }}
    {{- if not $config.jwt_secret }}
    {{- $_ := set $config "jwt_secret" .Values.global.jwt.secret }}
    {{- end }}
    {{- end }}
    {{- if and .Values.global .Values.global.initUser }}
    {{- if .Values.global.initUser.enabled }}
    {{- if not $config.built_in_auth }}
    {{- $_ := set $config "built_in_auth" dict }}
    {{- end }}
    {{- if not (index $config.built_in_auth "init_user") }}
    {{- $initUser := dict "email" .Values.global.initUser.email "password" .Values.global.initUser.password "name" .Values.global.initUser.name }}
    {{- $_ := set $config.built_in_auth "init_user" $initUser }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- $config | toYaml | nindent 4 }}
