apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edge-gateway.fullname" . }}-secrets
  labels:
    {{- include "edge-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.internalJwtKeySecretName }}
  labels:
    {{- include "edge-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  internal_jwt_private.key: ""
