affinity: {}
config:
    allowed_callers:
        - edge-gateway
        - scheduler
    health_check_period: 10s
    http_port: 8443
    log_level: info
    manager_url: http://manager.sandbox0-system:8080
    shutdown_timeout: 30s
    storage_proxy_url: http://storage-proxy.sandbox0-system:8081
fullnameOverride: ""
image:
    pullPolicy: IfNotPresent
    repository: sandbox0ai/infra
    tag: ""
imagePullSecrets: []
livenessProbe:
    httpGet:
        path: /healthz
        port: http
    initialDelaySeconds: 10
    periodSeconds: 10
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
readinessProbe:
    httpGet:
        path: /readyz
        port: http
    initialDelaySeconds: 5
    periodSeconds: 5
replicaCount: 1
resources:
    limits:
        cpu: 500m
        memory: 256Mi
    requests:
        cpu: 100m
        memory: 128Mi
secrets:
    internalJwtPrivateKeyKey: ""
    internalJwtPublicKeyKey: ""
    internalJwtPublicSecretName: ""
    internalJwtSecretName: ""
securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
service:
    port: 8443
    type: ClusterIP
serviceAccount:
    annotations: {}
    automount: true
    create: true
    name: ""
tolerations: []
