replicaCount: 1

image:
  repository: sandbox0ai/infra
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: "infra-operator"

serviceAccount:
  create: true
  annotations: {}
  name: "infra-operator"

podAnnotations: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

rbac:
  rules:
    - apiGroups:
      - ""
      resources:
      - configmaps
      - events
      - namespaces
      - nodes
      - persistentvolumeclaims
      - pods
      - pods/exec
      - secrets
      - serviceaccounts
      - services
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - admissionregistration.k8s.io
      resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - apps
      resources:
      - daemonsets
      - deployments
      - statefulsets
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - coordination.k8s.io
      resources:
      - leases
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - infra.sandbox0.ai
      resources:
      - sandbox0infras
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - infra.sandbox0.ai
      resources:
      - sandbox0infras/finalizers
      verbs:
      - update
    - apiGroups:
      - infra.sandbox0.ai
      resources:
      - sandbox0infras/status
      verbs:
      - get
      - patch
      - update
    - apiGroups:
      - networking.k8s.io
      resources:
      - ingresses
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - rbac.authorization.k8s.io
      resources:
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - sandbox0.ai
      resources:
      - sandboxtemplates
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch

nodeSelector: {}

tolerations: []

affinity: {}

config:
  imageRepo: "sandbox0ai/infra"
