replicaCount: 1

image:
  repository: sandbox0ai/infra
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: "infra-operator"

serviceAccount:
  create: true
  annotations: {}
  name: "infra-operator"

podAnnotations: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

config:
  # For infra services: edge-gateway, internal-gateway, manager, storage-proxy, netd, etc.
  imageRepo: "sandbox0ai/infra"
  imagePullPolicy: ""
