// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.1
// source: storage-proxy/pkg/s0fs/state_v2.proto

package s0fs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateV2Role int32

const (
	StateV2Role_STATE_V2_ROLE_UNSPECIFIED StateV2Role = 0
	StateV2Role_STATE_V2_ROLE_HEAD        StateV2Role = 1
	StateV2Role_STATE_V2_ROLE_MANIFEST    StateV2Role = 2
	StateV2Role_STATE_V2_ROLE_SNAPSHOT    StateV2Role = 3
)

// Enum value maps for StateV2Role.
var (
	StateV2Role_name = map[int32]string{
		0: "STATE_V2_ROLE_UNSPECIFIED",
		1: "STATE_V2_ROLE_HEAD",
		2: "STATE_V2_ROLE_MANIFEST",
		3: "STATE_V2_ROLE_SNAPSHOT",
	}
	StateV2Role_value = map[string]int32{
		"STATE_V2_ROLE_UNSPECIFIED": 0,
		"STATE_V2_ROLE_HEAD":        1,
		"STATE_V2_ROLE_MANIFEST":    2,
		"STATE_V2_ROLE_SNAPSHOT":    3,
	}
)

func (x StateV2Role) Enum() *StateV2Role {
	p := new(StateV2Role)
	*p = x
	return p
}

func (x StateV2Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateV2Role) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes[0].Descriptor()
}

func (StateV2Role) Type() protoreflect.EnumType {
	return &file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes[0]
}

func (x StateV2Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateV2Role.Descriptor instead.
func (StateV2Role) EnumDescriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{0}
}

type StateV2ChunkKind int32

const (
	StateV2ChunkKind_STATE_V2_CHUNK_KIND_UNSPECIFIED StateV2ChunkKind = 0
	StateV2ChunkKind_STATE_V2_CHUNK_KIND_NODES       StateV2ChunkKind = 1
	StateV2ChunkKind_STATE_V2_CHUNK_KIND_DIRECTORIES StateV2ChunkKind = 2
	StateV2ChunkKind_STATE_V2_CHUNK_KIND_DATA        StateV2ChunkKind = 3
	StateV2ChunkKind_STATE_V2_CHUNK_KIND_COLD_FILES  StateV2ChunkKind = 4
	StateV2ChunkKind_STATE_V2_CHUNK_KIND_SEGMENTS    StateV2ChunkKind = 5
)

// Enum value maps for StateV2ChunkKind.
var (
	StateV2ChunkKind_name = map[int32]string{
		0: "STATE_V2_CHUNK_KIND_UNSPECIFIED",
		1: "STATE_V2_CHUNK_KIND_NODES",
		2: "STATE_V2_CHUNK_KIND_DIRECTORIES",
		3: "STATE_V2_CHUNK_KIND_DATA",
		4: "STATE_V2_CHUNK_KIND_COLD_FILES",
		5: "STATE_V2_CHUNK_KIND_SEGMENTS",
	}
	StateV2ChunkKind_value = map[string]int32{
		"STATE_V2_CHUNK_KIND_UNSPECIFIED": 0,
		"STATE_V2_CHUNK_KIND_NODES":       1,
		"STATE_V2_CHUNK_KIND_DIRECTORIES": 2,
		"STATE_V2_CHUNK_KIND_DATA":        3,
		"STATE_V2_CHUNK_KIND_COLD_FILES":  4,
		"STATE_V2_CHUNK_KIND_SEGMENTS":    5,
	}
)

func (x StateV2ChunkKind) Enum() *StateV2ChunkKind {
	p := new(StateV2ChunkKind)
	*p = x
	return p
}

func (x StateV2ChunkKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateV2ChunkKind) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes[1].Descriptor()
}

func (StateV2ChunkKind) Type() protoreflect.EnumType {
	return &file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes[1]
}

func (x StateV2ChunkKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateV2ChunkKind.Descriptor instead.
func (StateV2ChunkKind) EnumDescriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{1}
}

type StateV2FileType int32

const (
	StateV2FileType_STATE_V2_FILE_TYPE_UNSPECIFIED  StateV2FileType = 0
	StateV2FileType_STATE_V2_FILE_TYPE_DIRECTORY    StateV2FileType = 1
	StateV2FileType_STATE_V2_FILE_TYPE_FILE         StateV2FileType = 2
	StateV2FileType_STATE_V2_FILE_TYPE_SYMLINK      StateV2FileType = 3
	StateV2FileType_STATE_V2_FILE_TYPE_FIFO         StateV2FileType = 4
	StateV2FileType_STATE_V2_FILE_TYPE_CHAR_DEVICE  StateV2FileType = 5
	StateV2FileType_STATE_V2_FILE_TYPE_BLOCK_DEVICE StateV2FileType = 6
	StateV2FileType_STATE_V2_FILE_TYPE_SOCKET       StateV2FileType = 7
)

// Enum value maps for StateV2FileType.
var (
	StateV2FileType_name = map[int32]string{
		0: "STATE_V2_FILE_TYPE_UNSPECIFIED",
		1: "STATE_V2_FILE_TYPE_DIRECTORY",
		2: "STATE_V2_FILE_TYPE_FILE",
		3: "STATE_V2_FILE_TYPE_SYMLINK",
		4: "STATE_V2_FILE_TYPE_FIFO",
		5: "STATE_V2_FILE_TYPE_CHAR_DEVICE",
		6: "STATE_V2_FILE_TYPE_BLOCK_DEVICE",
		7: "STATE_V2_FILE_TYPE_SOCKET",
	}
	StateV2FileType_value = map[string]int32{
		"STATE_V2_FILE_TYPE_UNSPECIFIED":  0,
		"STATE_V2_FILE_TYPE_DIRECTORY":    1,
		"STATE_V2_FILE_TYPE_FILE":         2,
		"STATE_V2_FILE_TYPE_SYMLINK":      3,
		"STATE_V2_FILE_TYPE_FIFO":         4,
		"STATE_V2_FILE_TYPE_CHAR_DEVICE":  5,
		"STATE_V2_FILE_TYPE_BLOCK_DEVICE": 6,
		"STATE_V2_FILE_TYPE_SOCKET":       7,
	}
)

func (x StateV2FileType) Enum() *StateV2FileType {
	p := new(StateV2FileType)
	*p = x
	return p
}

func (x StateV2FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StateV2FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes[2].Descriptor()
}

func (StateV2FileType) Type() protoreflect.EnumType {
	return &file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes[2]
}

func (x StateV2FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StateV2FileType.Descriptor instead.
func (StateV2FileType) EnumDescriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{2}
}

type StateV2Header struct {
	state                protoimpl.MessageState    `protogen:"open.v1"`
	FormatVersion        uint32                    `protobuf:"varint,1,opt,name=format_version,json=formatVersion,proto3" json:"format_version,omitempty"`
	Role                 StateV2Role               `protobuf:"varint,2,opt,name=role,proto3,enum=sandbox0.s0fs.internal.StateV2Role" json:"role,omitempty"`
	VolumeId             string                    `protobuf:"bytes,3,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	BindingSha256        []byte                    `protobuf:"bytes,4,opt,name=binding_sha256,json=bindingSha256,proto3" json:"binding_sha256,omitempty"`
	NextSeq              uint64                    `protobuf:"varint,5,opt,name=next_seq,json=nextSeq,proto3" json:"next_seq,omitempty"`
	NextInode            uint64                    `protobuf:"varint,6,opt,name=next_inode,json=nextInode,proto3" json:"next_inode,omitempty"`
	ManifestSeq          uint64                    `protobuf:"varint,7,opt,name=manifest_seq,json=manifestSeq,proto3" json:"manifest_seq,omitempty"`
	CheckpointSeq        uint64                    `protobuf:"varint,8,opt,name=checkpoint_seq,json=checkpointSeq,proto3" json:"checkpoint_seq,omitempty"`
	CreatedAtSeconds     int64                     `protobuf:"varint,9,opt,name=created_at_seconds,json=createdAtSeconds,proto3" json:"created_at_seconds,omitempty"`
	CreatedAtNanos       int32                     `protobuf:"varint,10,opt,name=created_at_nanos,json=createdAtNanos,proto3" json:"created_at_nanos,omitempty"`
	Compression          string                    `protobuf:"bytes,11,opt,name=compression,proto3" json:"compression,omitempty"`
	EncryptionAlgorithm  string                    `protobuf:"bytes,12,opt,name=encryption_algorithm,json=encryptionAlgorithm,proto3" json:"encryption_algorithm,omitempty"`
	WrappedKey           []byte                    `protobuf:"bytes,13,opt,name=wrapped_key,json=wrappedKey,proto3" json:"wrapped_key,omitempty"`
	NoncePrefix          []byte                    `protobuf:"bytes,14,opt,name=nonce_prefix,json=noncePrefix,proto3" json:"nonce_prefix,omitempty"`
	Chunks               []*StateV2ChunkDescriptor `protobuf:"bytes,15,rep,name=chunks,proto3" json:"chunks,omitempty"`
	CommitId             string                    `protobuf:"bytes,16,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	StateDigest          string                    `protobuf:"bytes,17,opt,name=state_digest,json=stateDigest,proto3" json:"state_digest,omitempty"`
	ManifestDigest       string                    `protobuf:"bytes,18,opt,name=manifest_digest,json=manifestDigest,proto3" json:"manifest_digest,omitempty"`
	ParentManifestKey    string                    `protobuf:"bytes,19,opt,name=parent_manifest_key,json=parentManifestKey,proto3" json:"parent_manifest_key,omitempty"`
	ParentManifestDigest string                    `protobuf:"bytes,20,opt,name=parent_manifest_digest,json=parentManifestDigest,proto3" json:"parent_manifest_digest,omitempty"`
	ParentCommitId       string                    `protobuf:"bytes,21,opt,name=parent_commit_id,json=parentCommitId,proto3" json:"parent_commit_id,omitempty"`
	ParentGeneration     uint64                    `protobuf:"varint,22,opt,name=parent_generation,json=parentGeneration,proto3" json:"parent_generation,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StateV2Header) Reset() {
	*x = StateV2Header{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Header) ProtoMessage() {}

func (x *StateV2Header) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Header.ProtoReflect.Descriptor instead.
func (*StateV2Header) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{0}
}

func (x *StateV2Header) GetFormatVersion() uint32 {
	if x != nil {
		return x.FormatVersion
	}
	return 0
}

func (x *StateV2Header) GetRole() StateV2Role {
	if x != nil {
		return x.Role
	}
	return StateV2Role_STATE_V2_ROLE_UNSPECIFIED
}

func (x *StateV2Header) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *StateV2Header) GetBindingSha256() []byte {
	if x != nil {
		return x.BindingSha256
	}
	return nil
}

func (x *StateV2Header) GetNextSeq() uint64 {
	if x != nil {
		return x.NextSeq
	}
	return 0
}

func (x *StateV2Header) GetNextInode() uint64 {
	if x != nil {
		return x.NextInode
	}
	return 0
}

func (x *StateV2Header) GetManifestSeq() uint64 {
	if x != nil {
		return x.ManifestSeq
	}
	return 0
}

func (x *StateV2Header) GetCheckpointSeq() uint64 {
	if x != nil {
		return x.CheckpointSeq
	}
	return 0
}

func (x *StateV2Header) GetCreatedAtSeconds() int64 {
	if x != nil {
		return x.CreatedAtSeconds
	}
	return 0
}

func (x *StateV2Header) GetCreatedAtNanos() int32 {
	if x != nil {
		return x.CreatedAtNanos
	}
	return 0
}

func (x *StateV2Header) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *StateV2Header) GetEncryptionAlgorithm() string {
	if x != nil {
		return x.EncryptionAlgorithm
	}
	return ""
}

func (x *StateV2Header) GetWrappedKey() []byte {
	if x != nil {
		return x.WrappedKey
	}
	return nil
}

func (x *StateV2Header) GetNoncePrefix() []byte {
	if x != nil {
		return x.NoncePrefix
	}
	return nil
}

func (x *StateV2Header) GetChunks() []*StateV2ChunkDescriptor {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *StateV2Header) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *StateV2Header) GetStateDigest() string {
	if x != nil {
		return x.StateDigest
	}
	return ""
}

func (x *StateV2Header) GetManifestDigest() string {
	if x != nil {
		return x.ManifestDigest
	}
	return ""
}

func (x *StateV2Header) GetParentManifestKey() string {
	if x != nil {
		return x.ParentManifestKey
	}
	return ""
}

func (x *StateV2Header) GetParentManifestDigest() string {
	if x != nil {
		return x.ParentManifestDigest
	}
	return ""
}

func (x *StateV2Header) GetParentCommitId() string {
	if x != nil {
		return x.ParentCommitId
	}
	return ""
}

func (x *StateV2Header) GetParentGeneration() uint64 {
	if x != nil {
		return x.ParentGeneration
	}
	return 0
}

type StateV2ChunkDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          StateV2ChunkKind       `protobuf:"varint,1,opt,name=kind,proto3,enum=sandbox0.s0fs.internal.StateV2ChunkKind" json:"kind,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	EncodedSize   uint64                 `protobuf:"varint,4,opt,name=encoded_size,json=encodedSize,proto3" json:"encoded_size,omitempty"`
	StoredSize    uint64                 `protobuf:"varint,5,opt,name=stored_size,json=storedSize,proto3" json:"stored_size,omitempty"`
	RecordCount   uint64                 `protobuf:"varint,6,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`
	FirstInode    uint64                 `protobuf:"varint,7,opt,name=first_inode,json=firstInode,proto3" json:"first_inode,omitempty"`
	LastInode     uint64                 `protobuf:"varint,8,opt,name=last_inode,json=lastInode,proto3" json:"last_inode,omitempty"`
	EncodedSha256 []byte                 `protobuf:"bytes,9,opt,name=encoded_sha256,json=encodedSha256,proto3" json:"encoded_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2ChunkDescriptor) Reset() {
	*x = StateV2ChunkDescriptor{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2ChunkDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2ChunkDescriptor) ProtoMessage() {}

func (x *StateV2ChunkDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2ChunkDescriptor.ProtoReflect.Descriptor instead.
func (*StateV2ChunkDescriptor) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{1}
}

func (x *StateV2ChunkDescriptor) GetKind() StateV2ChunkKind {
	if x != nil {
		return x.Kind
	}
	return StateV2ChunkKind_STATE_V2_CHUNK_KIND_UNSPECIFIED
}

func (x *StateV2ChunkDescriptor) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *StateV2ChunkDescriptor) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StateV2ChunkDescriptor) GetEncodedSize() uint64 {
	if x != nil {
		return x.EncodedSize
	}
	return 0
}

func (x *StateV2ChunkDescriptor) GetStoredSize() uint64 {
	if x != nil {
		return x.StoredSize
	}
	return 0
}

func (x *StateV2ChunkDescriptor) GetRecordCount() uint64 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *StateV2ChunkDescriptor) GetFirstInode() uint64 {
	if x != nil {
		return x.FirstInode
	}
	return 0
}

func (x *StateV2ChunkDescriptor) GetLastInode() uint64 {
	if x != nil {
		return x.LastInode
	}
	return 0
}

func (x *StateV2ChunkDescriptor) GetEncodedSha256() []byte {
	if x != nil {
		return x.EncodedSha256
	}
	return nil
}

type StateV2Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*StateV2Node         `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Directories   []*StateV2Directory    `protobuf:"bytes,2,rep,name=directories,proto3" json:"directories,omitempty"`
	Data          []*StateV2Data         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	ColdFiles     []*StateV2ColdFile     `protobuf:"bytes,4,rep,name=cold_files,json=coldFiles,proto3" json:"cold_files,omitempty"`
	Segments      []*StateV2Segment      `protobuf:"bytes,5,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Chunk) Reset() {
	*x = StateV2Chunk{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Chunk) ProtoMessage() {}

func (x *StateV2Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Chunk.ProtoReflect.Descriptor instead.
func (*StateV2Chunk) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{2}
}

func (x *StateV2Chunk) GetNodes() []*StateV2Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *StateV2Chunk) GetDirectories() []*StateV2Directory {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *StateV2Chunk) GetData() []*StateV2Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StateV2Chunk) GetColdFiles() []*StateV2ColdFile {
	if x != nil {
		return x.ColdFiles
	}
	return nil
}

func (x *StateV2Chunk) GetSegments() []*StateV2Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type StateV2Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Type          StateV2FileType        `protobuf:"varint,2,opt,name=type,proto3,enum=sandbox0.s0fs.internal.StateV2FileType" json:"type,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	Nlink         uint32                 `protobuf:"varint,6,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Size          uint64                 `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	Target        string                 `protobuf:"bytes,8,opt,name=target,proto3" json:"target,omitempty"`
	AtimeSeconds  int64                  `protobuf:"varint,9,opt,name=atime_seconds,json=atimeSeconds,proto3" json:"atime_seconds,omitempty"`
	AtimeNanos    int32                  `protobuf:"varint,10,opt,name=atime_nanos,json=atimeNanos,proto3" json:"atime_nanos,omitempty"`
	MtimeSeconds  int64                  `protobuf:"varint,11,opt,name=mtime_seconds,json=mtimeSeconds,proto3" json:"mtime_seconds,omitempty"`
	MtimeNanos    int32                  `protobuf:"varint,12,opt,name=mtime_nanos,json=mtimeNanos,proto3" json:"mtime_nanos,omitempty"`
	CtimeSeconds  int64                  `protobuf:"varint,13,opt,name=ctime_seconds,json=ctimeSeconds,proto3" json:"ctime_seconds,omitempty"`
	CtimeNanos    int32                  `protobuf:"varint,14,opt,name=ctime_nanos,json=ctimeNanos,proto3" json:"ctime_nanos,omitempty"`
	Rdev          uint64                 `protobuf:"varint,15,opt,name=rdev,proto3" json:"rdev,omitempty"`
	Xattrs        []*StateV2Xattr        `protobuf:"bytes,16,rep,name=xattrs,proto3" json:"xattrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Node) Reset() {
	*x = StateV2Node{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Node) ProtoMessage() {}

func (x *StateV2Node) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Node.ProtoReflect.Descriptor instead.
func (*StateV2Node) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{3}
}

func (x *StateV2Node) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *StateV2Node) GetType() StateV2FileType {
	if x != nil {
		return x.Type
	}
	return StateV2FileType_STATE_V2_FILE_TYPE_UNSPECIFIED
}

func (x *StateV2Node) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *StateV2Node) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *StateV2Node) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *StateV2Node) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *StateV2Node) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StateV2Node) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *StateV2Node) GetAtimeSeconds() int64 {
	if x != nil {
		return x.AtimeSeconds
	}
	return 0
}

func (x *StateV2Node) GetAtimeNanos() int32 {
	if x != nil {
		return x.AtimeNanos
	}
	return 0
}

func (x *StateV2Node) GetMtimeSeconds() int64 {
	if x != nil {
		return x.MtimeSeconds
	}
	return 0
}

func (x *StateV2Node) GetMtimeNanos() int32 {
	if x != nil {
		return x.MtimeNanos
	}
	return 0
}

func (x *StateV2Node) GetCtimeSeconds() int64 {
	if x != nil {
		return x.CtimeSeconds
	}
	return 0
}

func (x *StateV2Node) GetCtimeNanos() int32 {
	if x != nil {
		return x.CtimeNanos
	}
	return 0
}

func (x *StateV2Node) GetRdev() uint64 {
	if x != nil {
		return x.Rdev
	}
	return 0
}

func (x *StateV2Node) GetXattrs() []*StateV2Xattr {
	if x != nil {
		return x.Xattrs
	}
	return nil
}

type StateV2Xattr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Xattr) Reset() {
	*x = StateV2Xattr{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Xattr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Xattr) ProtoMessage() {}

func (x *StateV2Xattr) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Xattr.ProtoReflect.Descriptor instead.
func (*StateV2Xattr) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{4}
}

func (x *StateV2Xattr) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StateV2Xattr) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type StateV2Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentInode   uint64                 `protobuf:"varint,1,opt,name=parent_inode,json=parentInode,proto3" json:"parent_inode,omitempty"`
	Children      []*StateV2Child        `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Directory) Reset() {
	*x = StateV2Directory{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Directory) ProtoMessage() {}

func (x *StateV2Directory) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Directory.ProtoReflect.Descriptor instead.
func (*StateV2Directory) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{5}
}

func (x *StateV2Directory) GetParentInode() uint64 {
	if x != nil {
		return x.ParentInode
	}
	return 0
}

func (x *StateV2Directory) GetChildren() []*StateV2Child {
	if x != nil {
		return x.Children
	}
	return nil
}

type StateV2Child struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Child) Reset() {
	*x = StateV2Child{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Child) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Child) ProtoMessage() {}

func (x *StateV2Child) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Child.ProtoReflect.Descriptor instead.
func (*StateV2Child) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{6}
}

func (x *StateV2Child) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StateV2Child) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type StateV2Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Data) Reset() {
	*x = StateV2Data{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Data) ProtoMessage() {}

func (x *StateV2Data) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Data.ProtoReflect.Descriptor instead.
func (*StateV2Data) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{7}
}

func (x *StateV2Data) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *StateV2Data) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StateV2Data) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StateV2ColdFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`
	Extents       []*StateV2Extent       `protobuf:"bytes,2,rep,name=extents,proto3" json:"extents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2ColdFile) Reset() {
	*x = StateV2ColdFile{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2ColdFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2ColdFile) ProtoMessage() {}

func (x *StateV2ColdFile) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2ColdFile.ProtoReflect.Descriptor instead.
func (*StateV2ColdFile) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{8}
}

func (x *StateV2ColdFile) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *StateV2ColdFile) GetExtents() []*StateV2Extent {
	if x != nil {
		return x.Extents
	}
	return nil
}

type StateV2Extent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SegmentId     string                 `protobuf:"bytes,1,opt,name=segment_id,json=segmentId,proto3" json:"segment_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Extent) Reset() {
	*x = StateV2Extent{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Extent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Extent) ProtoMessage() {}

func (x *StateV2Extent) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Extent.ProtoReflect.Descriptor instead.
func (*StateV2Extent) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{9}
}

func (x *StateV2Extent) GetSegmentId() string {
	if x != nil {
		return x.SegmentId
	}
	return ""
}

func (x *StateV2Extent) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StateV2Extent) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type StateV2Segment struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VolumeId      string                    `protobuf:"bytes,2,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	Key           string                    `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Length        uint64                    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Sha256        string                    `protobuf:"bytes,5,opt,name=sha256,proto3" json:"sha256,omitempty"`
	Encryption    *StateV2SegmentEncryption `protobuf:"bytes,6,opt,name=encryption,proto3" json:"encryption,omitempty"`
	InlineData    []byte                    `protobuf:"bytes,7,opt,name=inline_data,json=inlineData,proto3" json:"inline_data,omitempty"`
	ChunkSize     uint64                    `protobuf:"varint,8,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkSha256   [][]byte                  `protobuf:"bytes,9,rep,name=chunk_sha256,json=chunkSha256,proto3" json:"chunk_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateV2Segment) Reset() {
	*x = StateV2Segment{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2Segment) ProtoMessage() {}

func (x *StateV2Segment) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2Segment.ProtoReflect.Descriptor instead.
func (*StateV2Segment) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{10}
}

func (x *StateV2Segment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StateV2Segment) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *StateV2Segment) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StateV2Segment) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StateV2Segment) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *StateV2Segment) GetEncryption() *StateV2SegmentEncryption {
	if x != nil {
		return x.Encryption
	}
	return nil
}

func (x *StateV2Segment) GetInlineData() []byte {
	if x != nil {
		return x.InlineData
	}
	return nil
}

func (x *StateV2Segment) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *StateV2Segment) GetChunkSha256() [][]byte {
	if x != nil {
		return x.ChunkSha256
	}
	return nil
}

type StateV2SegmentEncryption struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Algorithm      string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	ChunkSize      uint64                 `protobuf:"varint,3,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	PlaintextSize  uint64                 `protobuf:"varint,4,opt,name=plaintext_size,json=plaintextSize,proto3" json:"plaintext_size,omitempty"`
	CiphertextSize uint64                 `protobuf:"varint,5,opt,name=ciphertext_size,json=ciphertextSize,proto3" json:"ciphertext_size,omitempty"`
	WrappedKey     []byte                 `protobuf:"bytes,6,opt,name=wrapped_key,json=wrappedKey,proto3" json:"wrapped_key,omitempty"`
	NoncePrefix    []byte                 `protobuf:"bytes,7,opt,name=nonce_prefix,json=noncePrefix,proto3" json:"nonce_prefix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateV2SegmentEncryption) Reset() {
	*x = StateV2SegmentEncryption{}
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateV2SegmentEncryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateV2SegmentEncryption) ProtoMessage() {}

func (x *StateV2SegmentEncryption) ProtoReflect() protoreflect.Message {
	mi := &file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateV2SegmentEncryption.ProtoReflect.Descriptor instead.
func (*StateV2SegmentEncryption) Descriptor() ([]byte, []int) {
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP(), []int{11}
}

func (x *StateV2SegmentEncryption) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StateV2SegmentEncryption) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *StateV2SegmentEncryption) GetChunkSize() uint64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *StateV2SegmentEncryption) GetPlaintextSize() uint64 {
	if x != nil {
		return x.PlaintextSize
	}
	return 0
}

func (x *StateV2SegmentEncryption) GetCiphertextSize() uint64 {
	if x != nil {
		return x.CiphertextSize
	}
	return 0
}

func (x *StateV2SegmentEncryption) GetWrappedKey() []byte {
	if x != nil {
		return x.WrappedKey
	}
	return nil
}

func (x *StateV2SegmentEncryption) GetNoncePrefix() []byte {
	if x != nil {
		return x.NoncePrefix
	}
	return nil
}

var File_storage_proxy_pkg_s0fs_state_v2_proto protoreflect.FileDescriptor

const file_storage_proxy_pkg_s0fs_state_v2_proto_rawDesc = "" +
	"\n" +
	"%storage-proxy/pkg/s0fs/state_v2.proto\x12\x16sandbox0.s0fs.internal\"\x96\a\n" +
	"\rStateV2Header\x12%\n" +
	"\x0eformat_version\x18\x01 \x01(\rR\rformatVersion\x127\n" +
	"\x04role\x18\x02 \x01(\x0e2#.sandbox0.s0fs.internal.StateV2RoleR\x04role\x12\x1b\n" +
	"\tvolume_id\x18\x03 \x01(\tR\bvolumeId\x12%\n" +
	"\x0ebinding_sha256\x18\x04 \x01(\fR\rbindingSha256\x12\x19\n" +
	"\bnext_seq\x18\x05 \x01(\x04R\anextSeq\x12\x1d\n" +
	"\n" +
	"next_inode\x18\x06 \x01(\x04R\tnextInode\x12!\n" +
	"\fmanifest_seq\x18\a \x01(\x04R\vmanifestSeq\x12%\n" +
	"\x0echeckpoint_seq\x18\b \x01(\x04R\rcheckpointSeq\x12,\n" +
	"\x12created_at_seconds\x18\t \x01(\x03R\x10createdAtSeconds\x12(\n" +
	"\x10created_at_nanos\x18\n" +
	" \x01(\x05R\x0ecreatedAtNanos\x12 \n" +
	"\vcompression\x18\v \x01(\tR\vcompression\x121\n" +
	"\x14encryption_algorithm\x18\f \x01(\tR\x13encryptionAlgorithm\x12\x1f\n" +
	"\vwrapped_key\x18\r \x01(\fR\n" +
	"wrappedKey\x12!\n" +
	"\fnonce_prefix\x18\x0e \x01(\fR\vnoncePrefix\x12F\n" +
	"\x06chunks\x18\x0f \x03(\v2..sandbox0.s0fs.internal.StateV2ChunkDescriptorR\x06chunks\x12\x1b\n" +
	"\tcommit_id\x18\x10 \x01(\tR\bcommitId\x12!\n" +
	"\fstate_digest\x18\x11 \x01(\tR\vstateDigest\x12'\n" +
	"\x0fmanifest_digest\x18\x12 \x01(\tR\x0emanifestDigest\x12.\n" +
	"\x13parent_manifest_key\x18\x13 \x01(\tR\x11parentManifestKey\x124\n" +
	"\x16parent_manifest_digest\x18\x14 \x01(\tR\x14parentManifestDigest\x12(\n" +
	"\x10parent_commit_id\x18\x15 \x01(\tR\x0eparentCommitId\x12+\n" +
	"\x11parent_generation\x18\x16 \x01(\x04R\x10parentGeneration\"\xd2\x02\n" +
	"\x16StateV2ChunkDescriptor\x12<\n" +
	"\x04kind\x18\x01 \x01(\x0e2(.sandbox0.s0fs.internal.StateV2ChunkKindR\x04kind\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12!\n" +
	"\fencoded_size\x18\x04 \x01(\x04R\vencodedSize\x12\x1f\n" +
	"\vstored_size\x18\x05 \x01(\x04R\n" +
	"storedSize\x12!\n" +
	"\frecord_count\x18\x06 \x01(\x04R\vrecordCount\x12\x1f\n" +
	"\vfirst_inode\x18\a \x01(\x04R\n" +
	"firstInode\x12\x1d\n" +
	"\n" +
	"last_inode\x18\b \x01(\x04R\tlastInode\x12%\n" +
	"\x0eencoded_sha256\x18\t \x01(\fR\rencodedSha256\"\xda\x02\n" +
	"\fStateV2Chunk\x129\n" +
	"\x05nodes\x18\x01 \x03(\v2#.sandbox0.s0fs.internal.StateV2NodeR\x05nodes\x12J\n" +
	"\vdirectories\x18\x02 \x03(\v2(.sandbox0.s0fs.internal.StateV2DirectoryR\vdirectories\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.sandbox0.s0fs.internal.StateV2DataR\x04data\x12F\n" +
	"\n" +
	"cold_files\x18\x04 \x03(\v2'.sandbox0.s0fs.internal.StateV2ColdFileR\tcoldFiles\x12B\n" +
	"\bsegments\x18\x05 \x03(\v2&.sandbox0.s0fs.internal.StateV2SegmentR\bsegments\"\xfe\x03\n" +
	"\vStateV2Node\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12;\n" +
	"\x04type\x18\x02 \x01(\x0e2'.sandbox0.s0fs.internal.StateV2FileTypeR\x04type\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x12\x14\n" +
	"\x05nlink\x18\x06 \x01(\rR\x05nlink\x12\x12\n" +
	"\x04size\x18\a \x01(\x04R\x04size\x12\x16\n" +
	"\x06target\x18\b \x01(\tR\x06target\x12#\n" +
	"\ratime_seconds\x18\t \x01(\x03R\fatimeSeconds\x12\x1f\n" +
	"\vatime_nanos\x18\n" +
	" \x01(\x05R\n" +
	"atimeNanos\x12#\n" +
	"\rmtime_seconds\x18\v \x01(\x03R\fmtimeSeconds\x12\x1f\n" +
	"\vmtime_nanos\x18\f \x01(\x05R\n" +
	"mtimeNanos\x12#\n" +
	"\rctime_seconds\x18\r \x01(\x03R\fctimeSeconds\x12\x1f\n" +
	"\vctime_nanos\x18\x0e \x01(\x05R\n" +
	"ctimeNanos\x12\x12\n" +
	"\x04rdev\x18\x0f \x01(\x04R\x04rdev\x12<\n" +
	"\x06xattrs\x18\x10 \x03(\v2$.sandbox0.s0fs.internal.StateV2XattrR\x06xattrs\"8\n" +
	"\fStateV2Xattr\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"w\n" +
	"\x10StateV2Directory\x12!\n" +
	"\fparent_inode\x18\x01 \x01(\x04R\vparentInode\x12@\n" +
	"\bchildren\x18\x02 \x03(\v2$.sandbox0.s0fs.internal.StateV2ChildR\bchildren\"8\n" +
	"\fStateV2Child\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\"U\n" +
	"\vStateV2Data\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"h\n" +
	"\x0fStateV2ColdFile\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12?\n" +
	"\aextents\x18\x02 \x03(\v2%.sandbox0.s0fs.internal.StateV2ExtentR\aextents\"^\n" +
	"\rStateV2Extent\x12\x1d\n" +
	"\n" +
	"segment_id\x18\x01 \x01(\tR\tsegmentId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\"\xb4\x02\n" +
	"\x0eStateV2Segment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tvolume_id\x18\x02 \x01(\tR\bvolumeId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x16\n" +
	"\x06length\x18\x04 \x01(\x04R\x06length\x12\x16\n" +
	"\x06sha256\x18\x05 \x01(\tR\x06sha256\x12P\n" +
	"\n" +
	"encryption\x18\x06 \x01(\v20.sandbox0.s0fs.internal.StateV2SegmentEncryptionR\n" +
	"encryption\x12\x1f\n" +
	"\vinline_data\x18\a \x01(\fR\n" +
	"inlineData\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\b \x01(\x04R\tchunkSize\x12!\n" +
	"\fchunk_sha256\x18\t \x03(\fR\vchunkSha256\"\x85\x02\n" +
	"\x18StateV2SegmentEncryption\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x03 \x01(\x04R\tchunkSize\x12%\n" +
	"\x0eplaintext_size\x18\x04 \x01(\x04R\rplaintextSize\x12'\n" +
	"\x0fciphertext_size\x18\x05 \x01(\x04R\x0eciphertextSize\x12\x1f\n" +
	"\vwrapped_key\x18\x06 \x01(\fR\n" +
	"wrappedKey\x12!\n" +
	"\fnonce_prefix\x18\a \x01(\fR\vnoncePrefix*|\n" +
	"\vStateV2Role\x12\x1d\n" +
	"\x19STATE_V2_ROLE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STATE_V2_ROLE_HEAD\x10\x01\x12\x1a\n" +
	"\x16STATE_V2_ROLE_MANIFEST\x10\x02\x12\x1a\n" +
	"\x16STATE_V2_ROLE_SNAPSHOT\x10\x03*\xdf\x01\n" +
	"\x10StateV2ChunkKind\x12#\n" +
	"\x1fSTATE_V2_CHUNK_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19STATE_V2_CHUNK_KIND_NODES\x10\x01\x12#\n" +
	"\x1fSTATE_V2_CHUNK_KIND_DIRECTORIES\x10\x02\x12\x1c\n" +
	"\x18STATE_V2_CHUNK_KIND_DATA\x10\x03\x12\"\n" +
	"\x1eSTATE_V2_CHUNK_KIND_COLD_FILES\x10\x04\x12 \n" +
	"\x1cSTATE_V2_CHUNK_KIND_SEGMENTS\x10\x05*\x99\x02\n" +
	"\x0fStateV2FileType\x12\"\n" +
	"\x1eSTATE_V2_FILE_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cSTATE_V2_FILE_TYPE_DIRECTORY\x10\x01\x12\x1b\n" +
	"\x17STATE_V2_FILE_TYPE_FILE\x10\x02\x12\x1e\n" +
	"\x1aSTATE_V2_FILE_TYPE_SYMLINK\x10\x03\x12\x1b\n" +
	"\x17STATE_V2_FILE_TYPE_FIFO\x10\x04\x12\"\n" +
	"\x1eSTATE_V2_FILE_TYPE_CHAR_DEVICE\x10\x05\x12#\n" +
	"\x1fSTATE_V2_FILE_TYPE_BLOCK_DEVICE\x10\x06\x12\x1d\n" +
	"\x19STATE_V2_FILE_TYPE_SOCKET\x10\aB8Z6github.com/sandbox0-ai/sandbox0/storage-proxy/pkg/s0fsb\x06proto3"

var (
	file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescOnce sync.Once
	file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescData []byte
)

func file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescGZIP() []byte {
	file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescOnce.Do(func() {
		file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_proxy_pkg_s0fs_state_v2_proto_rawDesc), len(file_storage_proxy_pkg_s0fs_state_v2_proto_rawDesc)))
	})
	return file_storage_proxy_pkg_s0fs_state_v2_proto_rawDescData
}

var file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_storage_proxy_pkg_s0fs_state_v2_proto_goTypes = []any{
	(StateV2Role)(0),                 // 0: sandbox0.s0fs.internal.StateV2Role
	(StateV2ChunkKind)(0),            // 1: sandbox0.s0fs.internal.StateV2ChunkKind
	(StateV2FileType)(0),             // 2: sandbox0.s0fs.internal.StateV2FileType
	(*StateV2Header)(nil),            // 3: sandbox0.s0fs.internal.StateV2Header
	(*StateV2ChunkDescriptor)(nil),   // 4: sandbox0.s0fs.internal.StateV2ChunkDescriptor
	(*StateV2Chunk)(nil),             // 5: sandbox0.s0fs.internal.StateV2Chunk
	(*StateV2Node)(nil),              // 6: sandbox0.s0fs.internal.StateV2Node
	(*StateV2Xattr)(nil),             // 7: sandbox0.s0fs.internal.StateV2Xattr
	(*StateV2Directory)(nil),         // 8: sandbox0.s0fs.internal.StateV2Directory
	(*StateV2Child)(nil),             // 9: sandbox0.s0fs.internal.StateV2Child
	(*StateV2Data)(nil),              // 10: sandbox0.s0fs.internal.StateV2Data
	(*StateV2ColdFile)(nil),          // 11: sandbox0.s0fs.internal.StateV2ColdFile
	(*StateV2Extent)(nil),            // 12: sandbox0.s0fs.internal.StateV2Extent
	(*StateV2Segment)(nil),           // 13: sandbox0.s0fs.internal.StateV2Segment
	(*StateV2SegmentEncryption)(nil), // 14: sandbox0.s0fs.internal.StateV2SegmentEncryption
}
var file_storage_proxy_pkg_s0fs_state_v2_proto_depIdxs = []int32{
	0,  // 0: sandbox0.s0fs.internal.StateV2Header.role:type_name -> sandbox0.s0fs.internal.StateV2Role
	4,  // 1: sandbox0.s0fs.internal.StateV2Header.chunks:type_name -> sandbox0.s0fs.internal.StateV2ChunkDescriptor
	1,  // 2: sandbox0.s0fs.internal.StateV2ChunkDescriptor.kind:type_name -> sandbox0.s0fs.internal.StateV2ChunkKind
	6,  // 3: sandbox0.s0fs.internal.StateV2Chunk.nodes:type_name -> sandbox0.s0fs.internal.StateV2Node
	8,  // 4: sandbox0.s0fs.internal.StateV2Chunk.directories:type_name -> sandbox0.s0fs.internal.StateV2Directory
	10, // 5: sandbox0.s0fs.internal.StateV2Chunk.data:type_name -> sandbox0.s0fs.internal.StateV2Data
	11, // 6: sandbox0.s0fs.internal.StateV2Chunk.cold_files:type_name -> sandbox0.s0fs.internal.StateV2ColdFile
	13, // 7: sandbox0.s0fs.internal.StateV2Chunk.segments:type_name -> sandbox0.s0fs.internal.StateV2Segment
	2,  // 8: sandbox0.s0fs.internal.StateV2Node.type:type_name -> sandbox0.s0fs.internal.StateV2FileType
	7,  // 9: sandbox0.s0fs.internal.StateV2Node.xattrs:type_name -> sandbox0.s0fs.internal.StateV2Xattr
	9,  // 10: sandbox0.s0fs.internal.StateV2Directory.children:type_name -> sandbox0.s0fs.internal.StateV2Child
	12, // 11: sandbox0.s0fs.internal.StateV2ColdFile.extents:type_name -> sandbox0.s0fs.internal.StateV2Extent
	14, // 12: sandbox0.s0fs.internal.StateV2Segment.encryption:type_name -> sandbox0.s0fs.internal.StateV2SegmentEncryption
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_storage_proxy_pkg_s0fs_state_v2_proto_init() }
func file_storage_proxy_pkg_s0fs_state_v2_proto_init() {
	if File_storage_proxy_pkg_s0fs_state_v2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_proxy_pkg_s0fs_state_v2_proto_rawDesc), len(file_storage_proxy_pkg_s0fs_state_v2_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_proxy_pkg_s0fs_state_v2_proto_goTypes,
		DependencyIndexes: file_storage_proxy_pkg_s0fs_state_v2_proto_depIdxs,
		EnumInfos:         file_storage_proxy_pkg_s0fs_state_v2_proto_enumTypes,
		MessageInfos:      file_storage_proxy_pkg_s0fs_state_v2_proto_msgTypes,
	}.Build()
	File_storage_proxy_pkg_s0fs_state_v2_proto = out.File
	file_storage_proxy_pkg_s0fs_state_v2_proto_goTypes = nil
	file_storage_proxy_pkg_s0fs_state_v2_proto_depIdxs = nil
}
