apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storage-proxy.fullname" . }}
  labels:
    {{- include "storage-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- $config := deepCopy .Values.config }}
    {{- if and .Values.global .Values.global.database }}
    {{- if not $config.database_url }}
    {{- $_ := set $config "database_url" .Values.global.database.url }}
    {{- end }}
    {{- end }}
    {{- if and .Values.global .Values.global.juicefs }}
    {{- if not $config.meta_url }}
    {{- $_ := set $config "meta_url" .Values.global.juicefs.meta_url }}
    {{- end }}
    {{- if not $config.s3_bucket }}
    {{- $_ := set $config "s3_bucket" .Values.global.juicefs.s3_bucket }}
    {{- end }}
    {{- if not $config.s3_region }}
    {{- $_ := set $config "s3_region" .Values.global.juicefs.s3_region }}
    {{- end }}
    {{- if not $config.s3_endpoint }}
    {{- $_ := set $config "s3_endpoint" .Values.global.juicefs.s3_endpoint }}
    {{- end }}
    {{- if not $config.s3_access_key }}
    {{- $_ := set $config "s3_access_key" .Values.global.juicefs.s3_access_key }}
    {{- end }}
    {{- if not $config.s3_secret_key }}
    {{- $_ := set $config "s3_secret_key" .Values.global.juicefs.s3_secret_key }}
    {{- end }}
    {{- if not $config.s3_session_token }}
    {{- $_ := set $config "s3_session_token" .Values.global.juicefs.s3_session_token }}
    {{- end }}
    {{- end }}
    {{- $config | toYaml | nindent 4 }}
