apiVersion: v1
kind: Secret
metadata:
  name: {{ include "storage-proxy.fullname" . }}-secrets
  labels:
    {{- include "storage-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  postgres-url: {{ .Values.secrets.postgresUrl | quote }}
  aws-access-key-id: {{ .Values.secrets.awsAccessKeyId | quote }}
  aws-secret-access-key: {{ .Values.secrets.awsSecretAccessKey | quote }}
