# Control-plane installation values
controlPlane:
  enabled: true
dataPlane:
  enabled: false

global:
  internalAuth:
    controlPlane:
      secretName: "sandbox0-internal-jwt-control-plane"
      privateKeyKey: "private.key"
      publicKeyKey: "public.key"

edge-gateway:
  enabled: true
  fullnameOverride: "edge-gateway"

scheduler:
  enabled: false
  fullnameOverride: "scheduler"

postgresql:
  enabled: true
  fullnameOverride: "postgresql"

rustfs:
  enabled: true
  fullnameOverride: "rustfs"
