# Data-plane installation values
controlPlane:
  enabled: false
dataPlane:
  enabled: true

global:
  internalAuth:
    controlPlane:
      secretName: "sandbox0-internal-jwt-control-plane"
      publicKeyKey: "public.key"
    dataPlane:
      secretName: "sandbox0-internal-jwt-data-plane"
      privateKeyKey: "private.key"
      publicKeyKey: "public.key"

internal-gateway:
  enabled: true

manager:
  enabled: true

storage-proxy:
  enabled: true

netd:
  enabled: true
