apiVersion: v2
name: manager
description: Manager - Kubernetes Operator for sandbox0 lifecycle management
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - sandbox0
  - operator
  - kubernetes
  - controller
maintainers:
  - name: sandbox0
