affinity: {}
config:
    bpf_fs_path: /sys/fs/bpf
    cluster_dns_cidr: ""
    dns_resolvers:
        - 8.8.8.8:53
    fail_closed: true
    health_port: 8080
    internal_gateway_cidr: ""
    kube_config: ""
    log_level: info
    metrics_port: 9090
    metrics_report_interval: 10s
    namespace: ""
    node_name: ""
    procd_port: 49983
    proxy_http_port: 18080
    proxy_https_port: 18443
    proxy_listen_addr: 0.0.0.0
    resync_period: 30s
    storage_proxy_cidr: ""
    use_ebpf: true
    use_edt: true
fullnameOverride: ""
healthService:
    port: 8080
    type: ClusterIP
image:
    pullPolicy: IfNotPresent
    repository: sandbox0ai/infra
    tag: ""
imagePullSecrets: []
livenessProbe:
    httpGet:
        path: /healthz
        port: health
    initialDelaySeconds: 10
    periodSeconds: 10
metricsService:
    port: 9090
    type: ClusterIP
nameOverride: ""
nodeSelector: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
rbac:
    create: true
readinessProbe:
    httpGet:
        path: /readyz
        port: health
    initialDelaySeconds: 5
    periodSeconds: 5
resources:
    limits:
        cpu: 200m
        memory: 256Mi
    requests:
        cpu: 50m
        memory: 64Mi
securityContext:
    capabilities:
        add:
            - NET_ADMIN
            - SYS_ADMIN
            - BPF
    privileged: true
serviceAccount:
    annotations: {}
    automount: true
    create: true
    name: ""
tolerations:
    - operator: Exists
updateStrategy:
    rollingUpdate:
        maxUnavailable: 1
    type: RollingUpdate
